#  Forward pass

__Автор задач: Блохин Н.В. (NVBlokhin@fa.ru)__

Материалы:
* Deep Learning with PyTorch (2020) Авторы: Eli Stevens, Luca Antiga, Thomas Viehmann
* https://pytorch.org/docs/stable/generated/torch.matmul.html
* https://machinelearningmastery.com/choose-an-activation-function-for-deep-learning/
* https://machinelearningmastery.com/loss-and-loss-functions-for-training-deep-learning-neural-networks/

## Задачи для совместного разбора

1\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте нейрон с заданными весами `weights` и `bias`. Пропустите вектор `inputs` через нейрон и выведите результат.

In [1]:
class Neuron:
  def __init__(self, weights, bias):
    # <создать атрибуты объекта weights и bias>
    pass

  def forward(self, inputs):
    return # <реализовать логику нейрона>


In [ ]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

2\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

In [ ]:
class ReLU:
  def forward(self, inputs):
    # <реализовать логику ReLU>
    pass

3\. Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)
где $Y_i$ - правильный ответ для примера $i$, $\hat{Y_i}$ - предсказание модели для примера $i$, $n$ - количество примеров в батче.

In [ ]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return # <реализовать логику MSE>

In [ ]:
y_pred = torch.tensor([1, 3, 5])
y_true = torch.tensor([2, 3, 4])

## Задачи для самостоятельного решения

### Cоздание полносвязных слоев

<p class="task" id="1_1"></p>

1\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения) и опциональным вектором смещения.

$$y = xW^T + b$$

Пропустите вектор `inputs` через слой и выведите результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [2]:
import torch as th

In [4]:
class Linear:
    def __init__(self, n_neurons, n_features, bias: bool = False):
        self.n_neurons = n_neurons
        self.n_features = n_features

        self.W = th.normal(0,1,size=[self.n_neurons,self.n_features])
        self.bias = bias * th.normal(0,1,size=[self.n_neurons])

    def forward(self, inputs):
        return inputs@self.W.T + self.bias

In [29]:
# inputs: batch_size(3) x 4
inputs = th.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

l = Linear(*inputs.shape)
l.forward(inputs)

tensor([[ -5.5419,  -2.6727,  -3.6796],
        [  8.9479,   6.1256, -12.4714],
        [  2.6875,   3.6606,   1.8357]])

<p class="task" id="1_2"></p>

1\.2 Используя решение предыдущей задачи, создайте 2 полносвязных слоя и пропустите тензор `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выберите произвольно, количество нейронов во втором слое выберите так, чтобы результатом прогона являлась матрица `batch_size x 7`.

In [8]:
l1 = Linear(9,4, True)
f1 = l1.forward(inputs)

l2 = Linear(7,9)
f2 = l2.forward(f1)

f2

tensor([[-1.4606e+01, -1.6309e+01, -2.2960e+01, -1.8519e+00, -4.8067e+00,
          9.7363e+00,  9.0718e+00],
        [-9.8192e+00, -1.3733e-02, -2.5315e+01,  8.4303e+00, -1.1045e+01,
          2.2833e+01,  4.3280e+00],
        [-9.5726e+00, -1.3757e+01, -2.1762e+01,  1.0030e+01,  9.7110e-01,
          6.0511e+00,  3.5186e+00]])

In [9]:
f2.shape

torch.Size([3, 7])

### Создание функций активации

<p class="task" id="2_1"></p>

2\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

$$\overrightarrow{x} = (x_1, ..., x_J)$$

Создайте матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров. Функция должна применяться переданной на вход матрице построчно.

In [10]:
class Softmax:
    def forward(self, inputs):
        return (th.exp(inputs).T / th.exp(inputs).sum(dim=1)).T

In [11]:
sm = Softmax()
sm.forward(inputs)

tensor([[0.0641, 0.1744, 0.4740, 0.2875],
        [0.0452, 0.9074, 0.0022, 0.0452],
        [0.0052, 0.3488, 0.6355, 0.0105]])

In [12]:
th.exp(inputs[0]) / th.exp(inputs[0]).sum()

tensor([0.0641, 0.1744, 0.4740, 0.2875])

In [13]:
th.exp(inputs[1]) / th.exp(inputs[1]).sum()

tensor([0.0452, 0.9074, 0.0022, 0.0452])

In [26]:
sm.forward(inputs).sum(axis=1)

tensor([1.0000, 1.0000, 1.0000])

<p class="task" id="2_1"></p>

2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создайте матрицу размера 4x3, заполненную числами из стандартного нормального распределения, и проверьте работоспособность функции активации.

In [47]:
class ELU:
    def __init__(self, alpha: float):
        self.alpha = alpha

    def forward(self, inputs):
      inputs1 = inputs.clone()
      inputs1[inputs1<0] = self.alpha * (th.exp(inputs1[inputs1<0])-1)
      return inputs1

In [48]:
sample = th.normal(0,1,(4,3))

elu = ELU(1)
elu.forward(sample)

tensor([[ 0.3569,  0.1971,  0.8180],
        [ 0.4549, -0.1957,  1.1083],
        [-0.1708, -0.3570,  0.7115],
        [ 1.3089, -0.5310, -0.7009]])

In [49]:
sample

tensor([[ 0.3569,  0.1971,  0.8180],
        [ 0.4549, -0.2178,  1.1083],
        [-0.1873, -0.4416,  0.7115],
        [ 1.3089, -0.7572, -1.2070]])

### Создание функции потерь

<p class="task" id="3_1"></p>

3\.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализуйте функцию потерь CrossEntropyLoss:

$$y_i = (y_{i,1},...,y_{i,k})$$
<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

$$ CrossEntropyLoss = \frac{1}{n}\sum_{i=1}^{n}{L_i}$$
где $y_i$ - вектор правильных ответов для примера $i$, $\hat{y_i}$ - вектор предсказаний модели для примера $i$; $k$ - количество классов, $n$ - количество примеров в батче.

Создайте полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустите через функцию активации Softmax. Посчитайте значение функции потерь, трактуя вектор `y` как вектор правильных ответов.

In [141]:
class CrossEntropyLoss:
  def forward(self, y_pred, y_true):
    res = - (y_true * th.log(y_pred)).mean()
    return res

In [142]:
inputs = th.tensor([[1, 2, 3, 2.5],
                        [2, 5, -1, 2],
                        [-1.5, 2.7, 3.3, -0.8]])
y = th.tensor([1, 0, 0])

In [164]:
l1 = Linear(4,4, True)
f1 = l1.forward(inputs)

l2 = Linear(4,4)
f2 = l2.forward(f1)

l3 = Linear(2,4)
f3 = l3.forward(f2)

sm = Softmax()
y_pred = sm.forward(f3)
y_pred

tensor([[0.0064, 0.9936],
        [0.7659, 0.2341],
        [0.1732, 0.8268]])

In [165]:
CE = CrossEntropyLoss()
CE.forward(y_pred[:,1], y)

tensor(0.0022)

<p class="task" id="3_2"></p>

3.2 Модифицируйте MSE, добавив L2-регуляризацию.

$$MSE_R = MSE + \lambda\sum_{i=1}^{m}w_i^2$$

где $\lambda$ - коэффициент регуляризации; $w_i$ - веса модели.

In [169]:
class MSERegularized:
    def __init__(self, lambda_):
        self.lambda_ = lambda_

    def data_loss(self, y_pred, y_true):
        return ((y_pred-y_true)**2).mean()

    def reg_loss(self, weights):
        return self.lambda_ * (weights**2).sum()

    def forward(self, y_pred, y_true, weights):
        return self.data_loss(y_pred, y_true) + self.reg_loss(weights)

In [170]:
y_pred = th.tensor([-0.5, 1, 1.7])
y_true = th.tensor([0, 0.6, 2.3])
weights = th.normal(0, 5, (10, 1))

In [171]:
reg = MSERegularized(0.5)
reg.forward(y_pred, y_true, weights)

tensor(53.4906)

## Обратная связь
- [ ] Хочу получить обратную связь по решению